# render.yaml
services:
  - type: web
    name: qine-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:Qine-db%40123@db.tplcrjfpllbytqfmhrlf.supabase.co:5432/postgres
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000